# Generated by Django 4.0.2 on 2022-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rating_rating_shoppinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='shoppinglist',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='shoppinglist',
            field=models.ManyToManyField(default='', to='main.Ingredient', verbose_name='shoppinglist'),
        ),
    ]
