# Generated by Django 4.0.2 on 2022-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shoppinglist_shoppinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
    ]
