# Generated by Django 3.2.4 on 2022-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_shoppinglist_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='shoppinglist',
            field=models.ManyToManyField(default='', to='main.Amount', verbose_name='ShoppingList'),
        ),
    ]
