# Generated by Django 4.0.2 on 2022-03-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rating_rating'),
        ('main', '0008_alter_shoppinglist_shoppinglist'),
    ]

    operations = [
    ]
